name: Matrix

on:
 workflow_dispatch:

jobs:
 sample:
  strategy:
   matrix:
    os: [ 'ubuntu-latest', 'windows-latest' ]
  runs-on: ${{ matrix.os }}
  steps:
   - name: Display Text
     run: echo 'Hello Adi'
