name: GitHub Outputs

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set Color
          id: color_selector
          run: echo "COLOR=White" >> "$GITHUB_OUTPUT"
          
        - name: Get Color
          run: echo 'The selected color is ${{ steps.color_selector.outputs.COLOR }}'
