name: GitHub Outputs

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set Color
          id: color-selector
          run: echo 'Selected_Color=White' >> $GITHUB_OUTPUT

        - name: Get Color
          env:
            SELECTED_COLOR: ${{ steps.color-selector.outputs.Selected_Color }}
          run: echo 'The selected color is $SELECTED_COLOR'
