name: Reusable Workflow

on:
    workflow_call

env:
    Day: Monday

jobs:
    greeting_job:
        runs-on: ubuntu-latest
        env:
            Greeting: Hello
        steps:
            - name: "Say Hello"
              run: echo "$Greeting $Name, Today is $Day"
              env:
                Name: Adi
